// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFtUPccf810iPgcQsCLdU-NIf6ZQvHag',
    appId: '1:921924105765:web:bc107b8ac731616b64f1cc',
    messagingSenderId: '921924105765',
    projectId: 'elcharron-f969f',
    authDomain: 'elcharron-f969f.firebaseapp.com',
    storageBucket: 'elcharron-f969f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLFsbJbhFQj1M63bJY7c_LuQKnWmkyl4',
    appId: '1:921924105765:android:e21395946499544a64f1cc',
    messagingSenderId: '921924105765',
    projectId: 'elcharron-f969f',
    storageBucket: 'elcharron-f969f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8n1_9oTNKBlDwCYF5BTNLnR2KDtWDYxA',
    appId: '1:921924105765:ios:846c4b156a084b2764f1cc',
    messagingSenderId: '921924105765',
    projectId: 'elcharron-f969f',
    storageBucket: 'elcharron-f969f.firebasestorage.app',
    iosBundleId: 'com.example.elCharron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8n1_9oTNKBlDwCYF5BTNLnR2KDtWDYxA',
    appId: '1:921924105765:ios:846c4b156a084b2764f1cc',
    messagingSenderId: '921924105765',
    projectId: 'elcharron-f969f',
    storageBucket: 'elcharron-f969f.firebasestorage.app',
    iosBundleId: 'com.example.elCharron',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLFtUPccf810iPgcQsCLdU-NIf6ZQvHag',
    appId: '1:921924105765:web:f35f4b4331dfd3b164f1cc',
    messagingSenderId: '921924105765',
    projectId: 'elcharron-f969f',
    authDomain: 'elcharron-f969f.firebaseapp.com',
    storageBucket: 'elcharron-f969f.firebasestorage.app',
  );
}
